#! /bin/sh

# nitrogen | Wallpapers
nitrogen --set-zoom-fill Pictures/Wallpapers/winter.jpg
# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
# picom
picom --config $HOME/.config/picom/picom.conf &

bspc monitor -d I II III IV V VI VII VIII IX X

# polybar
.config/polybar/launch.sh &

setxkbmap 'us,ru,ua' -option 'grp:win_space_toggle'

bspc config border_width          2
bspc config window_gap            8

bspc config top_padding 40
bspc config left_padding 2
bspc config right_padding 2
bspc config bottom_padding 2

bspc config pointer_modifier mod4

bspc config split_ratio            0.5
bspc config focus_follows_pointer  true

